# Generated by Django 5.2 on 2025-05-01 17:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='deliverypersonnel',
            name='company',
        ),
    ]
