# Generated by Django 5.2 on 2025-06-03 14:08

import cloudinary.models
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_deliveryaddress_alter_order_delivery_address'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='subtotal',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='Subtotal'),
        ),
        migrations.AddField(
            model_name='order',
            name='total_cost',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='Total Cost'),
        ),
        migrations.AddField(
            model_name='order',
            name='transportation_mode',
            field=models.CharField(choices=[('bicycle', 'Bicycle'), ('keke_napep', 'Keke Napep (Tricycle)')], default='bicycle', max_length=20, verbose_name='Transportation Mode'),
        ),
        migrations.AddField(
            model_name='visitor',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='visitor',
            name='profile_image',
            field=cloudinary.models.CloudinaryField(blank=True, help_text='Optional profile picture', max_length=255, null=True, verbose_name='image'),
        ),
        migrations.AddField(
            model_name='visitor',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='delivery_cost',
            field=models.DecimalField(decimal_places=2, default=100.0, max_digits=10, verbose_name='Delivery Cost'),
        ),
    ]
