# Generated by Django 5.2 on 2025-05-01 22:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_remove_client_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='client',
        ),
        migrations.AddField(
            model_name='order',
            name='client_email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='client_name',
            field=models.CharField(default='no recipient', max_length=100),
        ),
        migrations.AddField(
            model_name='order',
            name='client_phone',
            field=models.CharField(default=0, max_length=15),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='role',
            field=models.CharField(choices=[('admin', 'Admin'), ('company', 'Company'), ('delivery', 'Delivery Personnel')], default='company', max_length=10),
        ),
    ]
