# Generated by Django 5.2 on 2025-06-03 14:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_order_subtotal_order_total_cost_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='visitor',
            name='profile_image',
        ),
    ]
