# Generated by Django 5.2 on 2025-05-02 08:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0004_remove_order_client_order_client_email_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='delivery_cost',
            field=models.FloatField(default=600, max_length=10),
        ),
        migrations.AddField(
            model_name='order',
            name='weight',
            field=models.FloatField(default=30.9, max_length=4),
        ),
    ]
